export default {
  topic: "poptalk",
  color: "#ed4c67",
  cards: [
    "What’s your guilty pleasure reality show?",
    "You can tell a lot about someone by their taste in music.",
    "Subtitles make every show better.",
    "Remakes are rarely better than the original.",
    "You should always finish a show you started, even if it’s bad.",
    "Video games are just as impactful as films.",
    "The Oscars are out of touch.",
    "It’s okay to judge someone by their Spotify playlist.",
    "Binge-watching kills the magic of a good series.",
    "TikTok is the future of pop culture.",
    "What movie do you quote way too often?",
    "What artist or band do you think is overrated?",
    "Which fictional character shaped your personality?",
    "What’s a trend you secretly hope never comes back?",
    "What pop song hits harder than it should?",
    "YouTube is replacing traditional TV.",
    "Streaming killed the album experience.",
    "People pretend to like certain shows just to fit in.",
    "Music sounds better when it’s nostalgic.",
    "Reality TV is just modern-day mythology.",
    "What’s a movie everyone loves but you secretly hate?",
    "Who’s your pop culture villain?",
    "Spotify Wrapped says more about you than your résumé.",
    "Memes are the new poetry.",
    "Social media trends have shorter lifespans than fruit flies."
  ]
};
