export default {
  topic: "wanderlust",
  color: "#118a7e",
  cards: [
    "Traveling alone is more rewarding than with others.",
    "You can truly understand a culture only by living there.",
    "The journey is always better than the destination.",
    "Touristy spots are worth the hype.",
    "Traveling should be a regular part of self-care.",
    "Every person should live in a new country at least once.",
    "Overplanning ruins the adventure.",
    "Nature-based travel beats urban exploration.",
    "Photos ruin the moment more than they preserve it.",
    "You learn more from travel than from formal education.",
    "What city changed the way you see the world?",
    "Where have you felt most out of your comfort zone?",
    "What’s the weirdest thing you’ve eaten while traveling?",
    "If you could only pack one thing, what would it be?",
    "Have you ever had a 'get me out of here' travel moment?",
    "What's your favorite airport ritual?",
    "Would you rather revisit your favorite place or try somewhere new?",
    "Does travel make you feel more like yourself or someone else?",
    "What’s your most chaotic travel story?",
    "Is getting lost part of the fun?",
    "What’s one country that surprised you in a good way?",
    "Is travel still travel if you're just posting it online?",
    "What’s your travel red flag?",
    "Would you ever quit your job to travel the world?",
    "What’s your favorite way to document a trip — if any?"
  ]
};
